### ISSUE TITLE
Autocmd Issues with Fugitive

### ISSUE THREAD

**Issue by asmodeus812** [ahmedkhalf/project.nvim#65] opened 2022-04-07 14:30 UTC
![image](https://user-images.githubusercontent.com/15955811/162222847-53467ff8-2f5a-46bc-9c06-02443c5bc361.png)
I am having problems with project nvim trying to resolve the current working dir in some temp buffers that fugitive opens. For example the Gdiff family or branch status etc. This breaks the fugitive functionality and is very annoying and a major blocker. I have no idea why this is happening though.

**Comment by Pustelto** [comment] 2022-10-04 19:42
Hi I have same issue. When I have this plugin active and I try to run `Gvdiffsplit!` to resolve merge conflicts using fugitive nothing will happen. Any chance to have a look at this? 🙏

**Comment by tpope** [comment] 2022-10-05 19:52
Have not reproduced, but this logic is sus:

https://github.com/ahmedkhalf/project.nvim/blob/628de7e433dd503e782831fe150bb750e56e55d6/lua/project_nvim/project.lua#L216-L232

Lots of buffers—Fugitive, HTTP, zip file entry, etc—will have an empty `buftype` but still not correspond to a real file. Ignoring URLs would be a good first step.

**Comment by SethGower** [comment] 2022-11-03 14:39
I am also having this issue. Not much else I can offer, just wanted to see if this has any plans of being resolved.

**Comment by captainko** [comment] 2023-01-13 01:55
Hi @ahmedkhalf could you please check this one out

**Comment by schrc3b6** [comment] 2023-04-04 00:06
I'm also having this issue and there seems to be an open pull request #78 that fixes the issue.

After looking into the code, I noticed the exclude_dir config can be used to also exclude protocols.
So for a workaround, you can set this in your project config:
```
	exclude_dirs = { "fugitive://*", "scp://*" },
```

@ahmedkhalf merging #78 would be great :)

**Comment by ahmedkhalf** [comment] 2023-04-04 00:20
Merged

**Closed** 2023-04-04 00:20 UTC

**Comment by Pustelto** [comment] 2023-04-21 05:39
Cool will give it a try and let you know thanks 🙏.
